# Site settings
# These are used to personalize your new site.
title: Mack Wessels
logo: "/images/mack_picture.jpg?raw=true"
description: > # your text below (remove <br /> elements if you don't need line breaks)
  Software Developer Portfolio<br />
  Projects in systems programming, web development, and game design.<br />
  Skills: C, C++, Java, SQL, React, Godot; Linux-focused development.
  <br /><br />
  <a href="/pdf/MW_Resume.pdf">View My Resume</a>
  <br />
  <a href="mailto:mackwessels@gmail.com?subject=Portfolio%20Inquiry">Email Me</a>
  <br />
repository: "csci-csu/csci-portfolio"
github_username: MackWessels
google_analytics: UA-000000-0

# Build setting
theme: jekyll-theme-minimal


